name: Auto-release for accepted tickets
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
  push:

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: install npm packages
        run: |
          npm i axios
          npm i nodemailer

      - name: auto-release
        uses: actions/github-script@v4
        with:
          script: |
            const axios = require("axios");
            const nodemailer = require("nodemailer");
            const regex = new RegExp('LAMBDA-[0-9]+', 'gim');
            const {owner, repo} = context.repo;
            const jiraToken = Buffer.from("${{secrets.JIRA_MILOS_AUTH}}").toString('base64');

            const mailer = nodemailer.createTransport({
              host: "${{secrets.SMTP_HOST}}",
              port: ${{secrets.SMTP_PORT}},
              secure: true,
              auth: {
                user: "${{secrets.SMTP_USERNAME}}",
                pass: "${{secrets.SMTP_PASSWORD}}"
              }
            });

            const pulls = (await github.pulls.list({ owner, repo, state: "open", base: "master" })).data;
            console.info(`Open PRs: ${pulls.map(p => p.number)}`);

            for (const pull of pulls) {
              const matches = pull.title.match(regex);
              if (!matches) {
                console.info(`PR #${pull.number}: title does not contain a ticket key. SKIP.`);
                continue;
              }

              const labels = await github.issues.listLabelsOnIssue({ owner, repo, issue_number: pull.number });
              if (labels.data.some(l => l.name === "no auto-release")) {
                console.info(`PR #${pull.number}: labeled with 'no auto-release'. SKIP.`);
                continue;
              }

              const issueKey = matches[0];
              const issue = (await axios.get(`https://rapid-engineering.atlassian.net/rest/api/latest/issue/${issueKey}`, {
                headers: { Authorization: `Basic ${jiraToken}` }
              })).data;

              if (issue.fields.resolution && issue.fields.resolution.name === 'Rejected') {
                console.info(`PR #${pull.number}: ticket is Rejected. CLOSE PR.`);
                await github.pulls.update({ owner, repo, pull_number: pull.number, state: 'closed' });
                continue;
              }

              if (!issue.fields.resolution || issue.fields.resolution.name !== 'Accepted') {
                console.info(`PR #${pull.number}: ticket is not Accepted yet. SKIP.`);
                continue;
              }

              if ((issue.fields.customfield_10165 && issue.fields.customfield_10165.value === 'Yes') ||
                  issue.fields.issuelinks.some(l => l.type.inward === 'Previous iteration of' && l.inwardIssue)) {
                console.info(`PR #${pull.number}: ticket has next iteration (Accept&Iterate flow). SKIP.`);
                continue;
              }
