name: Auto-release for accepted tickets
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
  push:

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: install npm packages
        run: |
          npm i axios
          npm i nodemailer

      - name: auto-release
        uses: actions/github-script@v4
        with:
          script: |
            const axios = require("axios");
            const nodemailer = require("nodemailer");
            const regex = new RegExp('LAMBDA-[0-9]+', 'gim');
            const {owner, repo} = context.repo;
            const jiraToken = Buffer.from("${{secrets.JIRA_MILOS_AUTH}}").toString('base64');

            const mailer = nodemailer.createTransport({
              host: "${{secrets.SMTP_HOST}}",
              port: ${{secrets.SMTP_PORT}},
              secure: true,
              auth: {
                user: "${{secrets.SMTP_USERNAME}}",
                pass: "${{secrets.SMTP_PASSWORD}}"
              }
            });
